# Спринт 7. Машинное обучение. Часть 2

Во второй части спринта мы научимся обучать модели. Расширим список зависимостей следующими пакетами:
- scikit-learn (sklean - фреймворк для машинного обучения; мы будем обучать с его помощью простые модели и деревья);
- tensorflow (фреймворк для глубокого обучения; мы будем обучать с его помощью нейронные сети).

Многие вещи вы можете уточнить в документации с рассматриваемым инструментам (конкретных ссылок давать не вижу смысла: вы можете гуглить названия моделей или названия классов и получить по каждой из них информацию).

Мы будем решать задачи обучения с учителем. Обучение будем выполнять на структурированных данных. К задачам обучения с учителем относят задачи:
- регрессии (нужно предсказать <b>число</b>, например, цену продажи дома)
- классификации (нужно предсказать <b>класс, к которому относится объект</b>, например, по комментарию на YouTube определить положительный это комментарий или нет)
![mach-learn.png](https://exponenta.ru/storage/app/media/uploaded-files/mach-learn.png)

Для задачи классификации будем использовать датасет с банковскими данными (из первой части). Предсказывать будем признак Attriction_Flag (бинарная классификация - 0 или 1). Для задачи регрессии будем использовать датасет с Kaggle, в котором представлены данные о стоимости квартир. Будем предсказывать стоимость квартиры на основе информации о ней.

Обращаю внимание - для обучения моделей мы используем предварительно обработанные данные! Предобработку банковского датасета мы произвели в первой части. Датасет для регрессии предобработан заранее.

In [515]:
# загрузим данные
import pandas as pd
data_regression = pd.read_csv("data/apartment_data_preprocessed.csv")
data_classification = pd.read_csv("data/bank_churners_preprocessed.csv")

In [516]:
data_regression

,Unnamed: 0,SalePrice,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,...,c_management_in_trust,c_self_management,c_Bangoge,c_Banwoldang,c_Chil-sung-market,c_Daegu,c_Kyungbuk_uni_hospital,c_Myung-duk,c_Sin-nam,c_no_subway_nearby
0,0,141592,2006,2007,8,814,3,111.0,184.0,1,...,1,0,0,0,0,0,1,0,0,0
1,1,51327,1985,2007,8,587,8,80.0,76.0,2,...,0,1,0,0,0,1,0,0,0,0
2,2,48672,1985,2007,8,587,6,80.0,76.0,2,...,0,1,0,0,0,1,0,0,0,0
3,3,380530,2006,2007,8,2056,8,249.0,536.0,2,...,1,0,0,0,0,0,0,0,1,0
4,4,221238,1993,2007,8,1761,3,523.0,536.0,2,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,5886,511504,2007,2017,8,1643,19,0.0,1270.0,2,...,1,0,0,0,0,0,1,0,0,0
5887,5887,298230,2006,2017,8,903,13,123.0,181.0,1,...,1,0,0,0,0,0,0,1,0,0
5888,5888,357522,2007,2017,8,868,20,0.0,1270.0,2,...,1,0,0,0,0,0,1,0,0,0
5889,5889,312389,1978,2017,8,1327,1,87.0,0.0,2,...,0,1,0,0,0,0,1,0,0,0
5890,5890,393805,2007,2017,8,868,13,0.0,1270.0,2,...,1,0,0,0,0,0,1,0,0,0

Задача - предсказать признак SalePrice (стоимость дома) по значениям оставшихся признаков.

In [517]:
data_classification

,Attrition_Flag,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,...,inc_$120K +,inc_$40K - $60K,inc_$60K - $80K,inc_$80K - $120K,inc_Less than $40K,inc_Unknown,card_Blue,card_Gold,card_Platinum,card_Silver
0,1,45,3,39,5,1,3,12691.0,777,11914.0,...,0,0,1,0,0,0,1,0,0,0
1,1,49,5,44,6,1,2,8256.0,864,7392.0,...,0,0,0,0,1,0,1,0,0,0
2,1,51,3,36,4,1,0,3418.0,0,3418.0,...,0,0,0,1,0,0,1,0,0,0
3,1,40,4,34,3,4,1,3313.0,2517,796.0,...,0,0,0,0,1,0,1,0,0,0
4,1,40,3,21,5,1,0,4716.0,0,4716.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,2,40,3,2,3,4003.0,1851,2152.0,...,0,1,0,0,0,0,1,0,0,0
10123,0,41,2,25,4,2,3,4277.0,2186,2091.0,...,0,1,0,0,0,0,1,0,0,0
10124,0,44,1,36,5,3,4,5409.0,0,5409.0,...,0,0,0,0,1,0,1,0,0,0
10125,0,30,2,36,4,3,3,5281.0,0,5281.0,...,0,1,0,0,0,0,1,0,0,0
10126,0,43,2,25,6,2,4,10388.0,1961,8427.0,...,0,0,0,0,1,0,0,0,0,1

Задача - предсказать признак Attrition_Flag (0 - клиент уйдет из банка, 1 - клиент останется) по значениям оставшихся признаков.

In [518]:
# немного подчистим данные для регрессии (удалим признак 'Unnamed: 0')
data_regression.drop(columns = ["Unnamed: 0"], inplace=True)
data_regression

,SalePrice,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,TimeToSubway,...,c_management_in_trust,c_self_management,c_Bangoge,c_Banwoldang,c_Chil-sung-market,c_Daegu,c_Kyungbuk_uni_hospital,c_Myung-duk,c_Sin-nam,c_no_subway_nearby
0,141592,2006,2007,8,814,3,111.0,184.0,1,2,...,1,0,0,0,0,0,1,0,0,0
1,51327,1985,2007,8,587,8,80.0,76.0,2,3,...,0,1,0,0,0,1,0,0,0,0
2,48672,1985,2007,8,587,6,80.0,76.0,2,3,...,0,1,0,0,0,1,0,0,0,0
3,380530,2006,2007,8,2056,8,249.0,536.0,2,4,...,1,0,0,0,0,0,0,0,1,0
4,221238,1993,2007,8,1761,3,523.0,536.0,2,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,511504,2007,2017,8,1643,19,0.0,1270.0,2,4,...,1,0,0,0,0,0,1,0,0,0
5887,298230,2006,2017,8,903,13,123.0,181.0,1,4,...,1,0,0,0,0,0,0,1,0,0
5888,357522,2007,2017,8,868,20,0.0,1270.0,2,4,...,1,0,0,0,0,0,1,0,0,0
5889,312389,1978,2017,8,1327,1,87.0,0.0,2,4,...,0,1,0,0,0,0,1,0,0,0
5890,393805,2007,2017,8,868,13,0.0,1270.0,2,4,...,1,0,0,0,0,0,1,0,0,0

## Подготовка обучающей и тестовой выборок

Решение любой задачи ML на структурированных данных начинается с выделения столбца, который мы хотим предсказывать.

In [519]:
# выделим целевой признак
y_regression = data_regression["SalePrice"]
y_regression

0       141592
1        51327
2        48672
3       380530
4       221238
         ...
5886    511504
5887    298230
5888    357522
5889    312389
5890    393805
Name: SalePrice, Length: 5891, dtype: int64

In [520]:
# выделим все, кроме целевого признака - по этим значениям будем предсказывать целевой признак
X_regression = data_regression.drop(columns = ['SalePrice'])
X_regression

,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,TimeToSubway,N_APT,...,c_management_in_trust,c_self_management,c_Bangoge,c_Banwoldang,c_Chil-sung-market,c_Daegu,c_Kyungbuk_uni_hospital,c_Myung-duk,c_Sin-nam,c_no_subway_nearby
0,2006,2007,8,814,3,111.0,184.0,1,2,3.0,...,1,0,0,0,0,0,1,0,0,0
1,1985,2007,8,587,8,80.0,76.0,2,3,1.0,...,0,1,0,0,0,1,0,0,0,0
2,1985,2007,8,587,6,80.0,76.0,2,3,1.0,...,0,1,0,0,0,1,0,0,0,0
3,2006,2007,8,2056,8,249.0,536.0,2,4,6.0,...,1,0,0,0,0,0,0,0,1,0
4,1993,2007,8,1761,3,523.0,536.0,2,1,8.0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,2007,2017,8,1643,19,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0
5887,2006,2017,8,903,13,123.0,181.0,1,4,3.0,...,1,0,0,0,0,0,0,1,0,0
5888,2007,2017,8,868,20,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0
5889,1978,2017,8,1327,1,87.0,0.0,2,4,2.0,...,0,1,0,0,0,0,1,0,0,0
5890,2007,2017,8,868,13,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0

In [521]:
# выделим целевой признак
y_classification = data_classification['Attrition_Flag']
y_classification

0        1
1        1
2        1
3        1
4        1
        ..
10122    1
10123    0
10124    0
10125    0
10126    0
Name: Attrition_Flag, Length: 10127, dtype: int64

In [522]:
# выделим все, кроме целевого признака - по этим значениям будем предсказывать целевой признак
X_classification = data_classification.drop(columns = ['Attrition_Flag'])
X_classification

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,inc_$120K +,inc_$40K - $60K,inc_$60K - $80K,inc_$80K - $120K,inc_Less than $40K,inc_Unknown,card_Blue,card_Gold,card_Platinum,card_Silver
0,45,3,39,5,1,3,12691.0,777,11914.0,1.335,...,0,0,1,0,0,0,1,0,0,0
1,49,5,44,6,1,2,8256.0,864,7392.0,1.541,...,0,0,0,0,1,0,1,0,0,0
2,51,3,36,4,1,0,3418.0,0,3418.0,2.594,...,0,0,0,1,0,0,1,0,0,0
3,40,4,34,3,4,1,3313.0,2517,796.0,1.405,...,0,0,0,0,1,0,1,0,0,0
4,40,3,21,5,1,0,4716.0,0,4716.0,2.175,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,50,2,40,3,2,3,4003.0,1851,2152.0,0.703,...,0,1,0,0,0,0,1,0,0,0
10123,41,2,25,4,2,3,4277.0,2186,2091.0,0.804,...,0,1,0,0,0,0,1,0,0,0
10124,44,1,36,5,3,4,5409.0,0,5409.0,0.819,...,0,0,0,0,1,0,1,0,0,0
10125,30,2,36,4,3,3,5281.0,0,5281.0,0.535,...,0,1,0,0,0,0,1,0,0,0
10126,43,2,25,6,2,4,10388.0,1961,8427.0,0.703,...,0,0,0,0,1,0,0,0,0,1

Теперь наборы данных разделен на 2 части - то, что предсказываем и то, по чему предсказываем. Перед началом обучения обычно всегда проивзодится еще одно действие - разделение набора данных на обучающую и тестирующую выборку.

Идея в том, что каждый из наборов X и y мы разделим на 2 части - на X_train, X_test и y_train, y_test соответственно. Для чего? Все просто.

Обучать модели мы будем на наборах X_train и y_train. А оценивать качество на наборах X_test и y_test, которые модели не видели в ходе обучения. Таким образом, мы сможем получать реалистичные предсказания и смотреть, как часто модель ошибается (вычислять значения метрик).

In [523]:
from sklearn.model_selection import train_test_split
# разобьем данные регрессии
X_regression_train, X_regression_test, y_regression_train, y_regression_test = train_test_split(X_regression,
                                                                                                y_regression,
                                                                                                test_size=0.2)
# указав параметр test_size = 0.2 получим, что 20% данных уйдут в тестовую выборку
# также в функцию можно передать параметр shuffle: по умолчанию функция рандомно
# перемешивает данные; поэтому и модели будут получаться разные;
# задайте параметр shuffle = False, если не хотите перемешивать

In [524]:
# разобьем данные классификации
# здесь используем стратификацию (stratify)
# при использовании стратификации распределение классов в обучающей и тестовой выборке будет одинаково
# это позволит получить более честное тестирование моделей
X_classification_train, X_classification_test, y_classification_train, y_classification_test = train_test_split(X_classification,
                                                                                                                y_classification,
                                                                                                                stratify=y,
                                                                                                                test_size=0.2)

In [525]:
len(X_regression_train), len(X_regression_test)

(4712, 1179)

In [526]:
len(X_classification_train), len(X_classification_test)

(8101, 2026)

Выборки готовы. Рассмотрим в этом разделе еще один момент. В некоторых случаях для повышения качества обучения имеет смысл скалирование (нормализация) данных (приведение значений каждого столбца выборки единому диапазону). При этом скалируем мы конечно же только данные, по которым получаем предсказания (X_train и X_test). Посмотрим сначала на данные до скалирования.

In [527]:
X_classification_train

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,inc_$120K +,inc_$40K - $60K,inc_$60K - $80K,inc_$80K - $120K,inc_Less than $40K,inc_Unknown,card_Blue,card_Gold,card_Platinum,card_Silver
8976,48,4,36,1,6,1,34516.0,0,34516.0,0.720,...,0,0,1,0,0,0,0,1,0,0
1692,54,2,45,5,2,4,2683.0,1671,1012.0,0.784,...,0,0,0,0,1,0,1,0,0,0
5967,55,4,36,5,3,3,7790.0,753,7037.0,0.968,...,0,0,0,0,0,1,1,0,0,0
8492,46,1,28,5,2,6,2069.0,0,2069.0,0.656,...,0,0,0,0,0,1,1,0,0,0
6332,43,3,25,5,1,2,10305.0,1870,8435.0,0.722,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,53,4,49,5,5,4,10533.0,330,10203.0,0.823,...,0,0,0,0,0,1,1,0,0,0
8643,43,4,35,3,3,0,6448.0,1464,4984.0,0.615,...,0,0,0,0,1,0,1,0,0,0
7026,59,0,53,3,2,0,1438.3,0,1438.3,0.896,...,0,1,0,0,0,0,1,0,0,0
2855,53,2,43,3,3,4,6853.0,1480,5373.0,0.513,...,0,0,0,0,1,0,1,0,0,0
8183,26,0,13,2,1,1,10254.0,0,10254.0,0.510,...,0,0,0,0,1,0,0,0,0,1

In [528]:
# выполним скалирование
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_regression_train_scaled = scaler.fit_transform(X_regression_train)
X_regression_test_scaled = scaler.transform(X_regression_train)
X_regression_train_scaled

array([[ 0.34646465,  0.1121064 ,  1.71619141, ..., -0.59238284,
         2.87356353, -0.27798346],
       [ 1.13901544,  1.14585464, -1.52072257, ..., -0.59238284,
        -0.34799996, -0.27798346],
       [ 0.2332431 ,  1.14585464,  0.24486687, ..., -0.59238284,
        -0.34799996, -0.27798346],
       ...,
       [-0.67252923, -0.23247635,  1.71619141, ..., -0.59238284,
        -0.34799996, -0.27798346],
       [ 0.2332431 , -0.92164184, -0.34366294, ..., -0.59238284,
        -0.34799996, -0.27798346],
       [-1.91796619, -0.57705909,  1.1276616 , ..., -0.59238284,
        -0.34799996, -0.27798346]])

Использование скалирования позволяет повысить качество в некоторых моделях (таких как логистическая регрессия и k ближайших соседей). Но в некоторых случаях, использование скалирования приведет к ухудшению качества получаемых моделей. Поэтому нужно исследовать данные и строить разные модели.

## Регрессионные модели в sklearn

In [529]:
# импортируем все модели, которые будем использовать
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, GradientBoostingRegressor

### Линейная регрессия без регуляризаторов

Самая простая модель - это линейная регрессия. Попробуем обучить такую модел

In [530]:
lr = LinearRegression().fit(X_regression_train, y_regression_train)

Некоторые из вас не поверят, но модель обучилась! Да, все настолько просто. Наверное, вам не терпиться проверить, а что получилось. Сможем ли мы предсказать цену какого-нибудь дома? Давайте попробуем.

In [531]:
# возьмем первый дом из тестовой выборки
lr.predict([X_regression_test.iloc[0]])

D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([240098.23093711])

Мы взяли первую строку (строку с номером 0) из тестовой выборки, обернули ее в список (потому что предсказания по умолчанию получаются для нескольких объектов) и получили предсказание цены.

Но можем ли мы быть уверены в качестве предсказания? Вдруг модель ошиблась? А на сколько она могла ошибиться. Для того, чтобы оценивать модели регрессии существуют метрики, которые вам рассказывали на лекции. Самые популярные: коэффициент детерминации, MAE (средняя абсолютная ошибка), MSE (средняя квадратичная ошибка). Давайте попробуем вычислить значения этих метрик для построенной модели.

In [532]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [533]:
# начнем с коэффициента детерминации. У любого регрессора в sklearn его можно
# получить методом score()
lr.score(X_regression_test, y_regression_test)

0.8851851851824428

Видим, что коэффициент детерминации близок к 1. Это говорит о качестве, потому что в идеальном случае (если бы модель предсказывала точно цены - что невозможно) значение коэффициента было бы 1. Проверим другие метрики.

In [534]:
# MAE
print(mean_absolute_error(y_regression_test, lr.predict(X_regression_test)))
# MSE
print(mean_squared_error(y_regression_test, lr.predict(X_regression_test)))

27668.825533232226
1314261468.360116

Попробуем другие модели. Дальше все будет похожим образом идти. Мы будем обучать модели с помощью fit на обучающих данных. Затем вычислять значения метрик и оценивать качество работы моделей.

### Линейная регрессия с регуляризацией (Ridge, Lasso)

Использование регуляризации позволяет в процессе минимизации функции ошибки не допускать больших значений у коэффициентов (весов) модели. Использование регуляризаторов позволяет избежать переобучения моделей.

В рассматриваемых моделях значение коэффициента регуляризации ($\alpha$) по умолчанию равно 1.

In [535]:
# обучим модель с L1-регуляризацией
ridge = Ridge().fit(X_regression_train, y_regression_train)
print(ridge.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, ridge.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, ridge.predict(X_regression_test)))

0.8853334859033326
27658.719120386988
1312563900.6420026

In [536]:
lasso = Lasso().fit(X_regression_train, y_regression_train)
print(lasso.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, lasso.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, lasso.predict(X_regression_test)))

D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.065e+12, tolerance: 5.316e+09
  model = cd_fast.enet_coordinate_descent(

0.8852081206428601
27659.677565881542
1313998930.8824086

Можем увидеть, что при параметре $\alpha$ по умолчанию, метрики качества ухудшились. На практике, нам часто необходимо подбирать оптимальные параметры модели для достижения наивысшего качества. В каком-то смысле - это и есть основная работа датасатаниста!
![datas.png](https://cs11.pikabu.ru/post_img/big/2020/06/08/10/1591639086168420987.jpg)

На примере подбора параметра $\alpha$ давайте расссмотрим, как подбирать гиперпараметры моделей. У каждой модели в sklearn есть свои параметры (их можно посмотреть в документации). Все будет аналогично

In [537]:
# импортируем класс GridSearchCV
# он позволит перебрать все комбинации параметров (значения для перебора мы зададим) и выбрать лучшую модель
from sklearn.model_selection import GridSearchCV

In [538]:
# создаем словарь, ключами которого являются названия параметров (напоминаю, их можно в документации посмотреть)
# а значениями - список из возможных значений (которые будут перебираться)
parameters = {'alpha': [0.25, 0.5, 0.75, 1]}

In [539]:
# оборачиваем нашу модель в объект GridSearchCV, туда же передаем словарь с параметрами и стартуем обучение
lasso_optimal = GridSearchCV(Lasso(), parameters).fit(X_regression_train, y_regression_train)
lasso_optimal.best_params_

D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.456e+12, tolerance: 4.303e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.464e+12, tolerance: 4.222e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.475e+12, tolerance: 4.238e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.453e+12, tolerance: 4.202e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.366e+12, tolerance: 4.297e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.459e+12, tolerance: 4.303e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.466e+12, tolerance: 4.222e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.477e+12, tolerance: 4.238e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.455e+12, tolerance: 4.202e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.368e+12, tolerance: 4.297e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.461e+12, tolerance: 4.303e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.468e+12, tolerance: 4.222e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.479e+12, tolerance: 4.238e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.457e+12, tolerance: 4.202e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.371e+12, tolerance: 4.297e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.463e+12, tolerance: 4.303e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.470e+12, tolerance: 4.222e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.481e+12, tolerance: 4.238e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.459e+12, tolerance: 4.202e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.373e+12, tolerance: 4.297e+09
  model = cd_fast.enet_coordinate_descent(
D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:634: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.057e+12, tolerance: 5.316e+09
  model = cd_fast.enet_coordinate_descent(

{'alpha': 0.25}

Варнинг - не ошибка :) Видимо, что при $\alpha$ = 0.25 должно достигаться наилучшее качество модели Lasso. Проверим.

In [540]:
print(lasso_optimal.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, lasso_optimal.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, lasso_optimal.predict(X_regression_test)))

0.885209769976131
27659.139909686783
1313980051.305155

Ну, конечно, не сильно лучше, но лучше. По крайней мере, мы теперь знаем, как подбирать параметры моделей.

### Деревья принятия решений

In [541]:
dt = DecisionTreeRegressor().fit(X_regression_train, y_regression_train)
print(dt.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, dt.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, dt.predict(X_regression_test)))

0.9697737049347002
11734.978356385862
345994155.8825073

Ну вот это уже куда лучше! Попробуем подобрать оптимальные параметры. Я говорил, что узнать список параметров можно в документации. Конкретно для этой модели здесь: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html

Все то, что можно передать в круглых скобках конструктору - это гиперпараметры. Их можно подобрать, ориентируяст на описание и тип данных. Давайте для примера попробуем подобрать два параметра.

In [542]:
parameters = {'max_features': [5, 10, 15, 20, 25, 30, 35, 40],
              'max_depth': [1, 2, 3, 4,  5, 6,  7, 8, 9, 10, 11, 12, 13, 14, 15]}

dt_optimal = GridSearchCV(DecisionTreeRegressor(), parameters).fit(X_regression_train, y_regression_train)
dt_optimal.best_params_

{'max_depth': 12, 'max_features': 35}

In [543]:
print(dt_optimal.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, dt_optimal.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, dt_optimal.predict(X_regression_test)))

0.971262064903242
11616.249013375935
328957206.7674259

Видим, что качество немного улучшилось. Можно поиграть с другими параметрами, но мы сейчас не будем этого делать.

### Ансамблевые модели

Ансамблевые модели представляют собой модели, состоящие из множества деревьев (принятия решений). При получении результата значение усредняется (в случае регрессии - среднее значение, в случае классификации - наиболее часто предсказанное значение).

По умолчанию ансамбли состоят из 10 деревьев. Количество деревьев является гиперпараметру и, как правило, подбирается.

In [544]:
# обучим модель бэггинга
bag = BaggingRegressor().fit(X_regression_train, y_regression_train)
print(bag.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, bag.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, bag.predict(X_regression_test)))

0.9805050110911335
9502.357991636802
223155111.03461754

In [545]:
# обучим модель градиентного бустинга
gb = GradientBoostingRegressor().fit(X_regression_train, y_regression_train)
print(gb.score(X_regression_test, y_regression_test))
print(mean_absolute_error(y_regression_test, gb.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, gb.predict(X_regression_test)))

0.9706539903181979
13420.954478415415
335917710.93478864

Мы рассмотрели несколько моделей, которые могут применяться для решения задачи регрессии. При этом мы должны понимать, что не всегда надо будет прибегать к деревьям и ансамблям для получения высокого качества - если в данных имеется линейная зависимость, то наилучшие результаты можно получить с помощью линейной регрессии.

## Классификаторы в sklearn

В этом разделе мы обучим простейшую модель KNN, модель логистической регрессии, а также применим ранее рассмотренные деревья (для классификации они также применяются).

### K ближайших соседей

Алгоритм KNN (k ближайших соседей) - это простейший метод классификации. Интересно то, что этот метод не требует какого-либо обучения. Он подразумевает хранение в себе тренировочных данных. Все расчеты проводятся при получении предсказания.

Итак, мы имеем обучающий набор данных. И хотим получить предсказание для нового объекта с помощью KNN. Что нужно сделать:
- определить значение параметра k (количество соседей)
- рассчитать расстояний между новым объектом (для которого хотим получить предсказание) и всеми остальными объектами из обучающей выборки (при этом расстояние рассчитывается также, как в школе считали расстояние между точками)
- когда у нас есть список из расстояний, мы сортируем их по возврастанию и выбираем первые k (то есть смотрим k ближайших объектов)
- чтобы получить предсказание, нам нужно просто выбрать класс, который чаще всего встречается у k ближайших соседей.

Постарайтесь понять идею алгоритма - он несложный и просто реализуется. Обращаю внимание еще раз на вычисление растояния. Формула как в школе. Пусть $x_{new}$ - объект, для которого получаем предсказание. А $x$ - это объект из обучающей выборки (напоминаю, что мы вычисляем расстояния для $x_{new}$ и всех объектов обучающей выборки).

Тогда формула для расстояний следующая: $d=\sqrt{Σ_{i=1}^{p}{(x_{new}^{i}-x^i)^2}}$, где p - количество признаков (столбцов в наборе данных, по которым мы предсказываем)

Одним из дополнительных заданий к этому спринту будет собственная реализация KNN. Пока будем использовать реализацию из KNN.

In [546]:
# здесь импортируем сами модели
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, GradientBoostingClassifier

# это функции, которые помогут оценивать качество моделей
from sklearn.metrics import confusion_matrix, classification_report

In [547]:
# количество соседей (k) - 9
knn = KNeighborsClassifier(n_neighbors=9).fit(X_classification_train, y_classification_train)

In [548]:
knn.predict([X_classification_test.iloc[0]])

D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

Предсказан класс 1 (клиент останется в банке). Но мы, также как и с регрессией, не может пока оценить качество модели. Давайте научимся это делать. Оценивать модели классификации мы можем с помощью матрицы путаницы (confusion matrix) и отчета со значениями основных метрик (classification report).

In [549]:
print(classification_report(y_classification_test, knn.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.69      0.56      0.62       325
           1       0.92      0.95      0.94      1701

    accuracy                           0.89      2026
   macro avg       0.81      0.76      0.78      2026
weighted avg       0.88      0.89      0.89      2026

В этом отчете мы можем увидеть общий процент принятия верных решений - accuracy. При этом, есть и другие метрики - precision, recall и их производная метрика f1. Анализируя значения этих метрик видим, что объекты второго класса (1) предсказываются с большей точностью, чем объекты первого класса (1). Очевидная причина этому - преобладание объектов класса 1 в обучающем наборе данных. Посмотрим, как можно наглядно посмотреть, сколько объектов какого класса было предсказано.

In [550]:
print(confusion_matrix(y_classification_test, knn.predict(X_classification_test)))

[[ 182  143]
 [  80 1621]]

Практически все объекты класса 1 предсказаны верно. А с первым классом модель ошибается. Попробуем сначала подобрать параметры (в данном случае - количество соседей).

In [551]:
parameters = {'n_neighbors': [3, 5, 7, 9]}

knn_optimal = GridSearchCV(KNeighborsClassifier(), parameters).fit(X_classification_train, y_classification_train)
knn_optimal.best_params_

{'n_neighbors': 9}

In [552]:
print(classification_report(y_classification_test, knn_optimal.predict(X_classification_test)))
print(confusion_matrix(y_classification_test, knn_optimal.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.69      0.56      0.62       325
           1       0.92      0.95      0.94      1701

    accuracy                           0.89      2026
   macro avg       0.81      0.76      0.78      2026
weighted avg       0.88      0.89      0.89      2026

[[ 182  143]
 [  80 1621]]

### Логистическая регрессия

Отмечу, что логистическая регрессия - это метод решения задачи классификации, но только для двух классов. Пусть название вас не запутывает.

In [553]:
lr = LogisticRegression().fit(X_classification_train, y_classification_train)
print(classification_report(y_classification_test, lr.predict(X_classification_test)))
print(confusion_matrix(y_classification_test, lr.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.69      0.45      0.55       325
           1       0.90      0.96      0.93      1701

    accuracy                           0.88      2026
   macro avg       0.79      0.71      0.74      2026
weighted avg       0.87      0.88      0.87      2026

[[ 147  178]
 [  67 1634]]

D:\Programs\Python\as_course_2022\ml_p2\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Деревья принятия решений и ансамбли

In [554]:
# деревья принятия решений
dt = DecisionTreeClassifier().fit(X_classification_train, y_classification_train)
print(classification_report(y_classification_test, dt.predict(X_classification_test)))
print(confusion_matrix(y_classification_test, dt.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.82      0.82      0.82       325
           1       0.97      0.97      0.97      1701

    accuracy                           0.94      2026
   macro avg       0.90      0.90      0.90      2026
weighted avg       0.94      0.94      0.94      2026

[[ 268   57]
 [  57 1644]]

In [555]:
# ансамбль (бэггинг)
bag = BaggingClassifier().fit(X_classification_train, y_classification_train)
print(classification_report(y_classification_test, bag.predict(X_classification_test)))
print(confusion_matrix(y_classification_test, bag.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       325
           1       0.97      0.97      0.97      1701

    accuracy                           0.95      2026
   macro avg       0.91      0.91      0.91      2026
weighted avg       0.95      0.95      0.95      2026

[[ 277   48]
 [  47 1654]]

In [556]:
# ансамбль (градиентный бустинг)
gb = GradientBoostingClassifier().fit(X_classification_train, y_classification_train)
print(classification_report(y_classification_test, gb.predict(X_classification_test)))
print(confusion_matrix(y_classification_test, gb.predict(X_classification_test)))

              precision    recall  f1-score   support

           0       0.93      0.85      0.89       325
           1       0.97      0.99      0.98      1701

    accuracy                           0.97      2026
   macro avg       0.95      0.92      0.93      2026
weighted avg       0.97      0.97      0.97      2026

[[ 277   48]
 [  21 1680]]

Градиентный бустинг показал лучший результат! Такую модель уже можно применять в реальных задачах.

## Глубокое обучение с Tensorflow

Глубокое обучение (deep learning) - это обучение глубоких нейронных сетей (глубокими нейронными сетями называют нейронные сети, состоящие из более чем одного скрытого слоя).
![mach-learn.png](https://neerc.ifmo.ru/wiki/images/thumb/6/63/Multi-layer-neural-net-scheme.png/500px-Multi-layer-neural-net-scheme.png)

Схема расчета значения одного нейрона (на основе значений нейронов предыдущего слоя).
![mach-learn.png](https://neerc.ifmo.ru/wiki/images/a/a5/%D0%98%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD_%D1%81%D1%85%D0%B5%D0%BC%D0%B0.png)

Предсказания нейронной сети - это значения нейронов выходного слоя (решая задачу классификации, мы размещаем на выходном слое 1 нейрон; решая задачу классификации - k нейронов, по количеству классов). Функции активации позволяют управлять множеством значений нейрона. Ниже приведены наиболее часто используемые функции активации.
![mach-learn.png](https://neurohive.io/wp-content/uploads/2018/07/funkcii-aktivacii-neironnoi-seti-570x257.png)

Обучаются нейронные сети методом обратного распространения ошибки. Он представляет собой оптимизацию (минимизацию) некоторой функции ошибки (loss-функции), которая вычисляется на основе полученных предсказаний и истинных значений. MSE, используемая как метрика в задаче регрессии, используется в качестве функции потерь при решении задачи регрессии. Для решения задачи классификации, как правило, используется категориальная кроссэнтропия (для случая двух классов - бинарная кроссэнтропия). Более подробно ознакомиться с этой функцией предлагаю самостоятельно.

Суть минимизации - вычисление антиградиента функции ошибки и выполнение шага градиентного спуска с целью обновления весов (градиент представляет собой вектор частных производных по всем весам). Основа Tensorflow (помимо структуры данных Тензор) - возможность эффективного автодифференцирования, с использованием ресурсов GPU.

Tensorflow автоматически по умолчанию использует GPU, если у вас GPU от NVidia и в системе установлены библиотеки CUDA и cuDNN.

Мы будем обучать сети без использования графического процессора.

### Решение задачи регрессии

In [557]:
X_regression

,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,TimeToSubway,N_APT,...,c_management_in_trust,c_self_management,c_Bangoge,c_Banwoldang,c_Chil-sung-market,c_Daegu,c_Kyungbuk_uni_hospital,c_Myung-duk,c_Sin-nam,c_no_subway_nearby
0,2006,2007,8,814,3,111.0,184.0,1,2,3.0,...,1,0,0,0,0,0,1,0,0,0
1,1985,2007,8,587,8,80.0,76.0,2,3,1.0,...,0,1,0,0,0,1,0,0,0,0
2,1985,2007,8,587,6,80.0,76.0,2,3,1.0,...,0,1,0,0,0,1,0,0,0,0
3,2006,2007,8,2056,8,249.0,536.0,2,4,6.0,...,1,0,0,0,0,0,0,0,1,0
4,1993,2007,8,1761,3,523.0,536.0,2,1,8.0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,2007,2017,8,1643,19,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0
5887,2006,2017,8,903,13,123.0,181.0,1,4,3.0,...,1,0,0,0,0,0,0,1,0,0
5888,2007,2017,8,868,20,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0
5889,1978,2017,8,1327,1,87.0,0.0,2,4,2.0,...,0,1,0,0,0,0,1,0,0,0
5890,2007,2017,8,868,13,0.0,1270.0,2,4,7.0,...,1,0,0,0,0,0,1,0,0,0

На входном слое у нас должно быть 40 нейронов (потому что один дом характеризуется 40 признаками). На выходном слое должен быть один нейрон, потому что мы предсказываем одно чисило (стоимость дома). Функция активации выходного слоя не должна никак ограничивать значение нейрона. Скрытых слоев может быть сколько угодно, в них может быть сколько угодно нейронов - мы сами это определяем. Построем нейросеть с помощью API Keras фреймворка Tensorflow.

In [558]:
model_regression = tf.keras.Sequential(
    [
        # Dense - полносвязный слой (каждый нейрон следующего слоя связан со всеми нейронами предыдущего)
        tf.keras.layers.Dense(64, activation="elu", input_shape=(40,)),
        # на втором скрытом слое будет 32 нейрона
        tf.keras.layers.Dense(32, activation="elu"),
        # Dropout позволяет внести фактор случайности - при обучении часть нейронов будет отключаться
        # каждый нейрон, в данном случае, будет отключаться с вероятностью 0.15
        tf.keras.layers.Dropout(0.15),
        tf.keras.layers.Dense(16, activation="elu"),
        tf.keras.layers.Dropout(0.2),
        # на выходе один нейрон
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [559]:
# посмотрим, какая сеть у нас получилась
model_regression.summary()

Model: "sequential_49"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_285 (Dense)           (None, 64)                2624

 dense_286 (Dense)           (None, 32)                2080

 dropout_92 (Dropout)        (None, 32)                0

 dense_287 (Dense)           (None, 16)                528

 dropout_93 (Dropout)        (None, 16)                0

 dense_288 (Dense)           (None, 1)                 17

=================================================================
Total params: 5,249
Trainable params: 5,249
Non-trainable params: 0
_________________________________________________________________

Видим количество обучаемых параметров каждого слоя и общее количество обучаемых параметров. Перед использованием модель необходимо скомпилировать, при этом указывается оптимизатор, скорость обучения (можно представлять как величину шага в методе градиентного спуска), функция потерь и метрики, которые мы хотим (при желании) вычислять в будущем методом evaluate()

In [560]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")

Мы готовы начинать обучения. В процессе обучения выключим логгирование (verbose=None). Основной параметр обучения - количеcтво эпох. Оно показывает, сколько раз модель пропустит через себя всю обучающую выборку. При этом существуют разные подходы к обучению - можно не просматривать всю выборку на одной эпохе, а генерировать каждый раз случайную подвыборку и обучаться на ней в рамках текущей эпохи. Это позволит сэкономить время обучения и предотвратить возможное переобучение.

In [561]:
model_regression.fit(X_regression_train, y_regression_train, epochs=10, verbose=None)

Проверим нашу модель с помощью метрик, которые использовали ранее.

In [562]:
print(mean_absolute_error(y_regression_test, model_regression.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, model_regression.predict(X_regression_test)))

37/37 [==============================] - 0s 889us/step
49449.41645462256
37/37 [==============================] - 0s 889us/step
3908539115.0854554

Видим, что результаты обучения есть, но они пока хуже моделей, которые мы рассматривали ранее. Попробуем изменить архитектуру сети и увеличить количество эпох.

In [563]:
model_regression = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(40,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dropout(0.025),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        # на выходе один нейрон
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss="mse")
model_regression.fit(X_regression_train, y_regression_train, epochs=50, verbose=None)
print(mean_absolute_error(y_regression_test, model_regression.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, model_regression.predict(X_regression_test)))

37/37 [==============================] - 0s 2ms/step
39878.246812712045
37/37 [==============================] - 0s 1ms/step
2682049371.76072

Мы получили наглядную демонстрацию важного факта - в некоторых задачах применение нейронных сетей менее целесообразно, чем использование более простых моделей. Но иногда они дают лучшие результаты. Важную роль еще играет подбор архитектуры и параметров.

### Решение задачи классификации

In [564]:
X_classification

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,inc_$120K +,inc_$40K - $60K,inc_$60K - $80K,inc_$80K - $120K,inc_Less than $40K,inc_Unknown,card_Blue,card_Gold,card_Platinum,card_Silver
0,45,3,39,5,1,3,12691.0,777,11914.0,1.335,...,0,0,1,0,0,0,1,0,0,0
1,49,5,44,6,1,2,8256.0,864,7392.0,1.541,...,0,0,0,0,1,0,1,0,0,0
2,51,3,36,4,1,0,3418.0,0,3418.0,2.594,...,0,0,0,1,0,0,1,0,0,0
3,40,4,34,3,4,1,3313.0,2517,796.0,1.405,...,0,0,0,0,1,0,1,0,0,0
4,40,3,21,5,1,0,4716.0,0,4716.0,2.175,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,50,2,40,3,2,3,4003.0,1851,2152.0,0.703,...,0,1,0,0,0,0,1,0,0,0
10123,41,2,25,4,2,3,4277.0,2186,2091.0,0.804,...,0,1,0,0,0,0,1,0,0,0
10124,44,1,36,5,3,4,5409.0,0,5409.0,0.819,...,0,0,0,0,1,0,1,0,0,0
10125,30,2,36,4,3,3,5281.0,0,5281.0,0.535,...,0,1,0,0,0,0,1,0,0,0
10126,43,2,25,6,2,4,10388.0,1961,8427.0,0.703,...,0,0,0,0,1,0,0,0,0,1

Нейронная сеть для решения задачи классификации будет очень похожа на ту сеть для регрессии, однако у нее по другому будет организован выходной слой. У нас есть 2 стратегии наполнения выходного слоя нейронами:
- при решении задачи бинарной классификации мы можем расположить на выходном слое один нейрон с функцией активации sigmoid (значения от 0 и 1), после чего округлять полученные значения; значение нейрона покажет уверенность сети в предсказании; также мы можем расположить 2 нейрона на выходном слое и применить функцию softmax. Тогда сумма значений нейронов выходного слоя будет 1, а предсказание мы сможем получить определив нейрон с наибольшим значением;
- в случае многоклассовой классификации, как правило, на выходном слое располагаются k нейронов (по количеству классов), функция активации - softmax; нейрон с наибольшим значением определяет предсказанный класс.

У нас задача бинарной классификации, попробуем обе стратегии.

In [565]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(37,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
# в качестве функции активации используется бинарная  кроссэнтропия
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="binary_crossentropy")
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None)

In [566]:
model_classification_1.predict(X_classification_test)[:5]

64/64 [==============================] - 0s 841us/step

array([[0.91047347],
       [0.55037457],
       [0.98337966],
       [0.7238046 ],
       [0.9876259 ]], dtype=float32)

In [567]:
y_pred = np.around(model_classification_1.predict(X_classification_test))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

64/64 [==============================] - 0s 889us/step
              precision    recall  f1-score   support

           0       0.77      0.07      0.13       325
           1       0.85      1.00      0.92      1701

    accuracy                           0.85      2026
   macro avg       0.81      0.53      0.53      2026
weighted avg       0.84      0.85      0.79      2026

[[  24  301]
 [   7 1694]]

Нейросеть отлично научилась выделять объекты более распространенного класса. Но в данных сильный дисбаланс и результаты отличаются от ожидаемых. Можем указать веса, которые будут использоваться при оптимизации функции ошибки. В качестве весов классов можно задать величины, обратные количеству элементов класса.

In [568]:
w0 = 1 / y_classification_train[y_classification_train==0].shape[0]
w1 = 1 / y_classification_train[y_classification_train==1].shape[0]

In [569]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(37,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="binary_crossentropy")
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None,
                           class_weight={0: w0, 1: w1})
y_pred = np.around(model_classification_1.predict(X_classification_test))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

64/64 [==============================] - 0s 904us/step
              precision    recall  f1-score   support

           0       0.32      0.83      0.46       325
           1       0.95      0.66      0.78      1701

    accuracy                           0.69      2026
   macro avg       0.64      0.74      0.62      2026
weighted avg       0.85      0.69      0.73      2026

[[ 270   55]
 [ 580 1121]]

Видим улучшения. Можем поиграть с архитектурой и параметрами и добиться еще более качественных результатов. Но напоследок давайте попробуем разместить 2 нейрона на выходном слое и использовать softmax в качестве функции активации.

In [570]:
model_classification_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(37,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 2 нейрона и softmax
        tf.keras.layers.Dense(2, activation="softmax"),
    ]
)
# в качестве функции активации используется категориальная кроссэнтропия
# используем разряженный (sparse) вариант, поскольку значения целевого признака не закодированы One-Hot кодированием
model_classification_2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="sparse_categorical_crossentropy")
model_classification_2.fit(X_classification_train, y_classification_train, epochs=25, verbose=None,
                           class_weight={0: w0, 1: w1})

In [571]:
model_classification_2.predict(X_classification_test)

64/64 [==============================] - 0s 895us/step

array([[4.4065073e-01, 5.5934930e-01],
       [7.7540159e-01, 2.2459842e-01],
       [2.0195828e-01, 7.9804176e-01],
       ...,
       [9.1622605e-05, 9.9990833e-01],
       [5.0095558e-01, 4.9904442e-01],
       [5.4765195e-01, 4.5234811e-01]], dtype=float32)

In [572]:
model_classification_2.predict(X_classification_test)[:5]

64/64 [==============================] - 0s 950us/step

array([[0.44065073, 0.5593493 ],
       [0.7754016 , 0.22459842],
       [0.20195828, 0.79804176],
       [0.6339752 , 0.3660248 ],
       [0.17549503, 0.82450503]], dtype=float32)

In [573]:
# получим индексы максимального значения для каждого элемента (вложенный массив) с помощью numpy
y_pred = [np.argmax(pred) for pred in model_classification_2.predict(X_classification_test)]

64/64 [==============================] - 0s 1ms/step

In [574]:
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

           0       0.31      0.82      0.45       325
           1       0.95      0.65      0.77      1701

    accuracy                           0.68      2026
   macro avg       0.63      0.74      0.61      2026
weighted avg       0.85      0.68      0.72      2026

[[ 268   57]
 [ 599 1102]]

Подведем итоги. В этом спринте мы разобрали вопросы, касающиеся анализа и подготовки данных, а также научились решать задачи регрессии и классификации с использованием различных моделей. Мы научились оценивать результаты работы моделей и подбору оптимальных параметров, использование которых способствует повышению качества.

Мы также познакомились с нейронными сетями и попробовали использовать их для решения наших задач.

Все это - лишь основы анализа данных и машинного обучения. Если вам захотелось разобраться во всем этом более подробно, вы всегда можете это сделать :)